//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Order.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And You&apos;ve Got.
        /// </summary>
        public static string AndYou_veGot {
            get {
                return ResourceManager.GetString("AndYou\'veGot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Add Range.
        /// </summary>
        public static string CanNotAddRange {
            get {
                return ResourceManager.GetString("CanNotAddRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is empty.
        /// </summary>
        public static string EmptyBadRequest {
            get {
                return ResourceManager.GetString("EmptyBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty field.
        /// </summary>
        public static string EmptyField {
            get {
                return ResourceManager.GetString("EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error While Refunding.
        /// </summary>
        public static string ErrorWhileRefunding {
            get {
                return ResourceManager.GetString("ErrorWhileRefunding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incorrect data.
        /// </summary>
        public static string IncorrectData {
            get {
                return ResourceManager.GetString("IncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incorrect information.
        /// </summary>
        public static string incorrectInformation {
            get {
                return ResourceManager.GetString("incorrectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Enough Points.
        /// </summary>
        public static string NotEnoughPoints {
            get {
                return ResourceManager.GetString("NotEnoughPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed.
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order cannot be canceled unless its status is &apos;Initiated&apos;.
        /// </summary>
        public static string OrderCannotBeCanceledUnlessItsStatusIsInitiated {
            get {
                return ResourceManager.GetString("OrderCannotBeCanceledUnlessItsStatusIsInitiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and the points you will earn is.
        /// </summary>
        public static string OrderPointsBeforePayment {
            get {
                return ResourceManager.GetString("OrderPointsBeforePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status Updated Successfully.
        /// </summary>
        public static string OrderStatusUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("OrderStatusUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchase completed successfully.
        /// </summary>
        public static string purchaseCompletedSuccessfully {
            get {
                return ResourceManager.GetString("purchaseCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful operation.
        /// </summary>
        public static string SuccessfulOperation {
            get {
                return ResourceManager.GetString("SuccessfulOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order has been delivered.
        /// </summary>
        public static string TheOrderHasBeenDelivered {
            get {
                return ResourceManager.GetString("TheOrderHasBeenDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order has been successfully canceled as the payment method is Cash..
        /// </summary>
        public static string TheOrderHasBeenSuccessfullyCanceledAsThePaymentMethodIsCash {
            get {
                return ResourceManager.GetString("TheOrderHasBeenSuccessfullyCanceledAsThePaymentMethodIsCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order has not yet been delivered.
        /// </summary>
        public static string Thisorderhasnotyetbeendelivered {
            get {
                return ResourceManager.GetString("Thisorderhasnotyetbeendelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Do not Have Any Order.
        /// </summary>
        public static string YouDonotHaveAnyOrder {
            get {
                return ResourceManager.GetString("YouDonotHaveAnyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have this product in your order.
        /// </summary>
        public static string YouDoNotHaveThisProductInYourOrder {
            get {
                return ResourceManager.GetString("YouDoNotHaveThisProductInYourOrder", resourceCulture);
            }
        }
    }
}
