//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Product.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  allTypes only allowed types.
        /// </summary>
        public static string AllowedImageTypes {
            get {
                return ResourceManager.GetString("AllowedImageTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must not be grater than 50 char.
        /// </summary>
        public static string CategoryNameMaxLength {
            get {
                return ResourceManager.GetString("CategoryNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is Duplicate data in the list.
        /// </summary>
        public static string DuplicateDataInList {
            get {
                return ResourceManager.GetString("DuplicateDataInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is empty.
        /// </summary>
        public static string EmptyBadRequest {
            get {
                return ResourceManager.GetString("EmptyBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty field.
        /// </summary>
        public static string EmptyField {
            get {
                return ResourceManager.GetString("EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date is required..
        /// </summary>
        public static string ExpireDateisrequired {
            get {
                return ResourceManager.GetString("ExpireDateisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incorrect data.
        /// </summary>
        public static string IncorrectData {
            get {
                return ResourceManager.GetString("IncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size is larger than allowed.
        /// </summary>
        public static string MaxSizeFiles {
            get {
                return ResourceManager.GetString("MaxSizeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Length Number Of Coupun  1.
        /// </summary>
        public static string MinNumOfCoupon {
            get {
                return ResourceManager.GetString("MinNumOfCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no categories are found.
        /// </summary>
        public static string NoCategoriesAreFound {
            get {
                return ResourceManager.GetString("NoCategoriesAreFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products found for the given vendor.
        /// </summary>
        public static string Noproductsfoundforthegivenvendor {
            get {
                return ResourceManager.GetString("Noproductsfoundforthegivenvendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Authorized.
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG Or JPG Or Jpeg.
        /// </summary>
        public static string PNGOrJPGOrJpeg {
            get {
                return ResourceManager.GetString("PNGOrJPGOrJpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Extension Not Found.
        /// </summary>
        public static string ProductExtensionNotFound {
            get {
                return ResourceManager.GetString("ProductExtensionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this name is already exist.
        /// </summary>
        public static string RedundantData {
            get {
                return ResourceManager.GetString("RedundantData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date cannot be after End Date..
        /// </summary>
        public static string StartDatecannotbeafterEndDate {
            get {
                return ResourceManager.GetString("StartDatecannotbeafterEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date cannot be after Expire Date..
        /// </summary>
        public static string StartDatecannotbeafterExpireDate {
            get {
                return ResourceManager.GetString("StartDatecannotbeafterExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date is required..
        /// </summary>
        public static string StartDateisrequired {
            get {
                return ResourceManager.GetString("StartDateisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful operation.
        /// </summary>
        public static string SuccessfulOperation {
            get {
                return ResourceManager.GetString("SuccessfulOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Product Is Not Available.
        /// </summary>
        public static string ThisProductIsNotAvailable {
            get {
                return ResourceManager.GetString("ThisProductIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors cannot get reviews for products they don&apos;t own.
        /// </summary>
        public static string VendorGetProductsReviewDoesNotOwn {
            get {
                return ResourceManager.GetString("VendorGetProductsReviewDoesNotOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors cannot add reviews to products they don&apos;t own.
        /// </summary>
        public static string VendorReviewOnProductDoesNotOwn {
            get {
                return ResourceManager.GetString("VendorReviewOnProductDoesNotOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Do Not Have This Product In Your Order.
        /// </summary>
        public static string YouDoNotHaveThisProductInYourOrder {
            get {
                return ResourceManager.GetString("YouDoNotHaveThisProductInYourOrder", resourceCulture);
            }
        }
    }
}
